AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.get
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: get

  GetIndex:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
  
  GetCustomer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: resource.get
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref CustomerTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /customer/{resourceId}
            Method: get

  PutCustomer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: resource.put
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref CustomerTable
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /customer/{resourceId}
            Method: put

  DeleteCustomer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: resource.delete
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref CustomerTable
      Events:
        DeleteResource:
          Type: Api
          Properties:
            Path: /customer/{resourceId}
            Method: delete

  CustomerTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
       PrimaryKey:
         Name: id
         Type: String